[theme]
base = "dark"
primaryColor = "#FF8C00"
backgroundColor = "#0a0e27"
secondaryBackgroundColor = "#131a3a"
textColor = "#F1F5F9"

[server]
maxUploadSize = 2000

[browser]
gatherUsageStats = false
